# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 300)
        MainWindow.setMinimumSize(QtCore.QSize(350, 300))
        MainWindow.setMaximumSize(QtCore.QSize(350, 300))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.text_VotingBallot = QtWidgets.QLabel(parent=self.centralwidget)
        self.text_VotingBallot.setGeometry(QtCore.QRect(70, 10, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.text_VotingBallot.setFont(font)
        self.text_VotingBallot.setObjectName("text_VotingBallot")
        self.text_ID = QtWidgets.QLabel(parent=self.centralwidget)
        self.text_ID.setGeometry(QtCore.QRect(30, 50, 35, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.text_ID.setFont(font)
        self.text_ID.setObjectName("text_ID")
        self.Input_ID = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Input_ID.setGeometry(QtCore.QRect(60, 50, 113, 20))
        self.Input_ID.setObjectName("Input_ID")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 80, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.radio_John = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radio_John.setGeometry(QtCore.QRect(70, 120, 62, 14))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radio_John.setFont(font)
        self.radio_John.setObjectName("radio_John")
        self.radio_Jane = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radio_Jane.setGeometry(QtCore.QRect(70, 140, 62, 14))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radio_Jane.setFont(font)
        self.radio_Jane.setObjectName("radio_Jane")
        self.button_submit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_submit.setGeometry(QtCore.QRect(60, 160, 121, 21))
        self.button_submit.setObjectName("button_submit")
        self.label_directions = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_directions.setGeometry(QtCore.QRect(40, 180, 181, 31))
        self.label_directions.setObjectName("label_directions")
        self.button_results = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_results.setGeometry(QtCore.QRect(60, 220, 121, 21))
        self.button_results.setObjectName("button_results")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.text_VotingBallot.setText(_translate("MainWindow", "Ballot"))
        self.text_ID.setText(_translate("MainWindow", "ID"))
        self.label.setText(_translate("MainWindow", "Candidate"))
        self.radio_John.setText(_translate("MainWindow", "John"))
        self.radio_Jane.setText(_translate("MainWindow", "Jane"))
        self.button_submit.setText(_translate("MainWindow", "Submit Vote"))
        self.label_directions.setText(_translate("MainWindow", "Select Candidate and Submit Vote"))
        self.button_results.setText(_translate("MainWindow", "Results"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
